# Gruvbox Material Hard — Kitty theme
foreground #d4be98
background #1d2021
cursor #d8a657

# Black / Dark Gray
color0 #1d2021
color8 #5a524c

# Red
color1 #ea6962
color9 #ea6962

# Green
color2 #a9b665
color10 #a9b665

# Yellow
color3 #d8a657
color11 #d8a657

# Blue
color4 #7daea3
color12 #7daea3

# Magenta
color5 #d3869b
color13 #d3869b

# Cyan
color6 #89b482
color14 #89b482

# White / Light Gray
color7 #d4be98
color15 #ebdbb2

# Selection
selection_foreground #1d2021
selection_background #5a524c
